import { useEffect, useMemo, useState } from 'react';
import { Download, Plus, Trash2, RefreshCw, X } from 'lucide-react';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { supabase } from '../lib/supabase';
import { useToast } from '../components/Toast';

const TRIARC_STATE = '36';
const money = n => Number(n || 0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const fmtDate = d => d ? new Date(d+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}) : '-';
const gstState = g => g && /^\d{2}/.test(g.trim()) ? g.trim().slice(0,2) : null;

function words(n){
 const o=['','One','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Eleven','Twelve','Thirteen','Fourteen','Fifteen','Sixteen','Seventeen','Eighteen','Nineteen'],t=['','','Twenty','Thirty','Forty','Fifty','Sixty','Seventy','Eighty','Ninety'];
 const w=x=>{x=Math.floor(x);if(!x)return '';if(x<20)return o[x];if(x<100)return t[Math.floor(x/10)]+(x%10?' '+o[x%10]:'');if(x<1000)return o[Math.floor(x/100)]+' Hundred'+(x%100?' '+w(x%100):'');if(x<1e5)return w(x/1e3)+' Thousand'+(x%1e3?' '+w(x%1e3):'');if(x<1e7)return w(x/1e5)+' Lakh'+(x%1e5?' '+w(x%1e5):'');return w(x/1e7)+' Crore'+(x%1e7?' '+w(x%1e7):'')};
 const r=Math.floor(n||0),p=Math.round(((n||0)-r)*100); return 'INR '+(w(r)||'Zero')+' Rupees'+(p?' and '+w(p)+' Paise':'')+' Only';
}
function calc(items,type){
 let taxable=0,cgst=0,sgst=0,igst=0;
 const rows=items.map(x=>{const gross=+x.quantity*+x.unit_price,disc=gross*(+x.discount_percent||0)/100,tx=gross-disc,tax=tx*(+x.gst_rate||0)/100;taxable+=tx;if(type==='IGST')igst+=tax;else{cgst+=tax/2;sgst+=tax/2}return {...x,taxable_amount:tx,discount_amount:disc,line_total:tx+tax}});
 const tax=cgst+sgst+igst,total=taxable+tax,round=Math.round(total)-total;
 return {rows,taxable,cgst,sgst,igst,tax,round,total:total+round};
}
function pdf(inv,items,cfg){
 const d=new jsPDF({unit:'mm',format:'a4'}),L=10,W=190,bg=[220,237,247];
 d.rect(L,8,W,281);d.setFillColor(...bg);d.rect(L,8,W,13,'F');d.setFont('helvetica','bold');d.setFontSize(15);d.text('Tax Invoice',105,16.5,{align:'center'});
 d.setFontSize(11);d.text(cfg?.business_name||'M/S. TRIARC GROUP',L+3,28);d.setFont('helvetica','normal');d.setFontSize(8);
 d.text([cfg?.address_line1,cfg?.address_line2,cfg?.city,cfg?.state,cfg?.pincode].filter(Boolean).join(', '),L+3,33);
 d.text('GSTIN: '+(cfg?.gstin||'36AAYFT2036P1ZB'),L+3,38);d.text('Contact: '+(cfg?.phone||'+91 7993356677'),L+3,42);
 d.setFont('helvetica','bold');d.text('Invoice No.',130,28);d.setFont('helvetica','normal');d.text(inv.invoice_number,160,28);
 d.setFont('helvetica','bold');d.text('Date',130,33);d.setFont('helvetica','normal');d.text(fmtDate(inv.invoice_date),160,33);
 d.setFont('helvetica','bold');d.text('Station',130,38);d.setFont('helvetica','normal');d.text(inv.station||'-',160,38);
 d.setFillColor(...bg);d.rect(L,47,W,7,'F');d.setFont('helvetica','bold');d.text('Buyer Details',L+3,52);
 d.setFontSize(8.5);d.text(inv.billing_name||'-',L+3,61);d.setFont('helvetica','normal');if(inv.billing_gstin)d.text('GSTIN: '+inv.billing_gstin,L+3,65.5);
 d.text([inv.billing_address_line1,inv.billing_address_line2,inv.billing_city,inv.billing_state,inv.billing_pincode].filter(Boolean).join(', '),L+3,70);
 d.setFont('helvetica','bold');d.text('Place of Supply:',125,61);d.setFont('helvetica','normal');d.text((inv.place_of_supply||'-')+(inv.place_of_supply_state_code?' ('+inv.place_of_supply_state_code+')':''),154,61);
 d.setFillColor(...bg);d.rect(L,76,W,7,'F');d.setFont('helvetica','bold');d.text('Billing Details',L+3,81);
 d.setFont('helvetica','normal');d.text('Station: '+(inv.station||'-'),L+3,89);d.text('Billing Period: '+fmtDate(inv.billing_period_from)+' - '+fmtDate(inv.billing_period_to),105,89);
 autoTable(d,{startY:93,margin:{left:L,right:10},head:[['Sr.','Description','HSN/SAC','Qty','Unit','Rate','GST%','Amount']],body:items.map((x,i)=>[i+1,x.description,x.hsn||'-',(+x.quantity).toFixed(3),x.unit||'PCS',money(x.unit_price),(+x.gst_rate||0)+'%',money(x.line_total)]),theme:'grid',styles:{fontSize:7.5,lineColor:[25,25,25],lineWidth:.25,cellPadding:2},headStyles:{fillColor:bg,textColor:[0,0,0]},columnStyles:{0:{cellWidth:9,halign:'center'},2:{cellWidth:18},3:{cellWidth:16,halign:'right'},4:{cellWidth:13},5:{cellWidth:23,halign:'right'},6:{cellWidth:15,halign:'center'},7:{cellWidth:27,halign:'right'}}});
 let y=d.lastAutoTable.finalY+5;d.setFont('helvetica','bold');d.setFontSize(8.5);d.text('Taxable Value',145,y);d.text(money(inv.taxable_amount),197,y,{align:'right'});y+=4.5;
 if(inv.igst_amount){d.text('IGST',145,y);d.text(money(inv.igst_amount),197,y,{align:'right'});y+=4.5}else{d.text('CGST',145,y);d.text(money(inv.cgst_amount),197,y,{align:'right'});y+=4.5;d.text('SGST',145,y);d.text(money(inv.sgst_amount),197,y,{align:'right'});y+=4.5}
 d.text('Round Off',145,y);d.text(money(inv.round_off),197,y,{align:'right'});y+=5;d.setFillColor(...bg);d.rect(137,y-1,60,8,'F');d.text('Total',145,y+4);d.text(money(inv.grand_total),197,y+4,{align:'right'});y+=13;
 d.setFontSize(8);d.text('Amount in Words:',L+3,y);d.setFont('helvetica','normal');d.text(words(inv.grand_total),L+35,y);y+=7;
 d.setFillColor(...bg);d.rect(L,y,W,7,'F');d.setFont('helvetica','bold');d.text('Tax Analysis',L+3,y+4.8);y+=7;
 const groups={};items.forEach(x=>{const k=x.hsn||'-';groups[k]??={taxable:0,gst:+x.gst_rate||0};groups[k].taxable+=+x.taxable_amount||0});
 const ig=!!inv.igst_amount;
 autoTable(d,{startY:y,margin:{left:L,right:10},head:[['HSN/SAC','Taxable Value','GST Rate','CGST','SGST','IGST','Total Tax']],body:Object.entries(groups).map(([h,g])=>{const tx=g.taxable*g.gst/100;return[h,money(g.taxable),g.gst+'%',ig?'-':money(tx/2),ig?'-':money(tx/2),ig?money(tx):'-',money(tx)]}),theme:'grid',styles:{fontSize:7.2,lineColor:[25,25,25],lineWidth:.25},headStyles:{fillColor:bg,textColor:[0,0,0]}});
 y=d.lastAutoTable.finalY+7;d.setFont('helvetica','bold');d.text('Declaration',L+3,y);d.setFont('helvetica','normal');d.setFontSize(7.5);d.text('This is a computer generated invoice. All particulars are as stated above.',L+3,y+4.5);d.setFont('helvetica','bold');d.text('Authorised Signatory',165,y+18,{align:'center'});d.setFontSize(7);d.setFont('helvetica','normal');d.text('This is a Computer Generated Invoice',105,285,{align:'center'});return d;
}
function Modal({title,children,onClose}){return <div className="modal-backdrop"><div className="modal-card"><div className="modal-header"><h3>{title}</h3><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>;}

export default function EVBilling(){
 const toast=useToast(),[tab,setTab]=useState('invoices'),[customers,setCustomers]=useState([]),[inventory,setInventory]=useState([]),[invoices,setInvoices]=useState([]),[settings,setSettings]=useState(null);
 const [customer,setCustomer]=useState(''),[series,setSeries]=useState('GST-26/27'),[station,setStation]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[manualTax,setManualTax]=useState('CGST_SGST'),[items,setItems]=useState([]),[saving,setSaving]=useState(false);
 const [customerModal,setCustomerModal]=useState(false),[inventoryModal,setInventoryModal]=useState(false),[assetModal,setAssetModal]=useState(false),[customerSaving,setCustomerSaving]=useState(false),[inventorySaving,setInventorySaving]=useState(false),[assetSaving,setAssetSaving]=useState(false),[editingCustomer,setEditingCustomer]=useState(null),[editingInventory,setEditingInventory]=useState(null),[editingAsset,setEditingAsset]=useState(null),[assets,setAssets]=useState([]);
 const emptyCustomerForm={name:'',gstin:'',pan:'',billing_address_line1:'',billing_city:'',billing_state:'',billing_pincode:'',place_of_supply:'',customer_state_code:''};
 const [customerForm,setCustomerForm]=useState(emptyCustomerForm);
 const emptyInventoryForm={product_name:'DC EV Charging',hsn:'996749',unit:'KWH',purchase_price:'',selling_price:'',gst_rate:'18',notes:'',inventory_type:'electricity'}; const [inventoryForm,setInventoryForm]=useState(emptyInventoryForm);
 const emptyAssetForm={asset_type:'charger',name:'',manufacturer:'',model:'',serial_number:'',asset_tag:'',site:'',location:'',status:'active',purchase_date:'',installation_date:'',warranty_start:'',warranty_end:'',ip_address:'',mac_address:'',firmware_version:'',notes:'',details:{rated_power_kw:'',connector_type:'',connector_count:'',input_voltage:'',output_voltage:'',max_current:'',meter_serial:'',ocpp_version:'',network_type:'',camera_resolution:'',lens:'',poe:'',nvr_channels:'',storage_capacity:'',hdd_serial:'',hdd_count:'',poe_ports:'',connected_cameras:''}}; const [assetForm,setAssetForm]=useState(emptyAssetForm);
 const load=async()=>{const [a,b,c,s,e]=await Promise.all([supabase.from('billing_customers').select('*').eq('active',true).order('name'),supabase.from('billing_invoices').select('*').order('invoice_date',{ascending:false}),supabase.from('inventory').select('*').eq('active',true).eq('inventory_type','electricity').order('product_name'),supabase.from('billing_settings').select('*').limit(1).maybeSingle(),supabase.from('ev_assets').select('*').order('asset_type').order('name')]);const err=[a,b,c,s,e].find(x=>x.error);if(err)throw err.error;setAssets(e.data||[]);setCustomers(a.data||[]);setInvoices(b.data||[]);setInventory(c.data||[]);setSettings(s.data)};
 useEffect(()=>{load().catch(e=>toast.error(e.message))},[]);
 const c=customers.find(x=>x.id===customer),auto=gstState(c?.gstin),taxType=auto?(auto===TRIARC_STATE?'CGST_SGST':'IGST'):manualTax,total=useMemo(()=>calc(items,taxType),[items,taxType]);
 const add=()=>{const p=inventory[0];if(!p)return toast.error('Add an inventory item first.');setItems(x=>[...x,{inventory_id:p.id,description:p.product_name,hsn:p.hsn||'',unit:p.unit||'PCS',quantity:1,unit_price:+p.selling_price||0,gst_rate:+p.gst_rate||0,discount_percent:0}])};
 const pick=(i,id)=>{const p=inventory.find(x=>x.id===id);if(!p)return;setItems(x=>x.map((r,n)=>n===i?{...r,inventory_id:p.id,description:p.product_name,hsn:p.hsn||'',unit:p.unit||'PCS',unit_price:+p.selling_price||0,gst_rate:+p.gst_rate||0}:r))};
 const openCustomer=(row=null)=>{setEditingCustomer(row);setCustomerForm(row?{name:row.name||'',gstin:row.gstin||'',pan:row.pan||'',billing_address_line1:row.billing_address_line1||'',billing_city:row.billing_city||'',billing_state:row.billing_state||'',billing_pincode:row.billing_pincode||'',place_of_supply:row.place_of_supply||'',customer_state_code:row.customer_state_code||''}:emptyCustomerForm);setCustomerModal(true)};
 const openAsset=(row=null)=>{setEditingAsset(row);setAssetForm(row?{...emptyAssetForm,...row,details:{...emptyAssetForm.details,...(row.details||{})}}:emptyAssetForm);setAssetModal(true)};
 const saveAsset=async ev=>{ev.preventDefault();if(!assetForm.name.trim())return toast.error('Enter asset name.');setAssetSaving(true);try{const payload={asset_type:assetForm.asset_type,name:assetForm.name.trim(),manufacturer:assetForm.manufacturer.trim()||null,model:assetForm.model.trim()||null,serial_number:assetForm.serial_number.trim()||null,asset_tag:assetForm.asset_tag.trim()||null,site:assetForm.site.trim()||null,location:assetForm.location.trim()||null,status:assetForm.status,purchase_date:assetForm.purchase_date||null,installation_date:assetForm.installation_date||null,warranty_start:assetForm.warranty_start||null,warranty_end:assetForm.warranty_end||null,ip_address:assetForm.ip_address.trim()||null,mac_address:assetForm.mac_address.trim()||null,firmware_version:assetForm.firmware_version.trim()||null,notes:assetForm.notes.trim()||null,details:assetForm.details};const q=editingAsset?supabase.from('ev_assets').update(payload).eq('id',editingAsset.id):supabase.from('ev_assets').insert(payload);const {data,error}=await q.select().single();if(error)throw error;setAssets(x=>(editingAsset?x.map(r=>r.id===data.id?data:r):[...x,data]).sort((a,b)=>a.asset_type.localeCompare(b.asset_type)||a.name.localeCompare(b.name)));setAssetModal(false);setEditingAsset(null);setAssetForm(emptyAssetForm);toast.success(editingAsset?'Asset updated':'Asset added')}catch(e){toast.error(e.message||'Asset save failed')}finally{setAssetSaving(false)}};
 const deleteAsset=async row=>{if(!window.confirm('Delete '+row.name+'?'))return;const {error}=await supabase.from('ev_assets').delete().eq('id',row.id);if(error)return toast.error(error.message);setAssets(x=>x.filter(r=>r.id!==row.id));toast.success('Asset deleted')};
 const openInventory=(row=null)=>{setEditingInventory(row);if(row){setInventoryForm({product_name:row.product_name||'DC EV Charging',hsn:'996749',unit:'KWH',purchase_price:row.purchase_price??'',selling_price:row.selling_price??'',gst_rate:row.gst_rate??'18',notes:row.notes||'',inventory_type:'electricity'});}else{setInventoryForm(emptyInventoryForm);}setInventoryModal(true)};
 const addCustomer=async e=>{e.preventDefault();if(!customerForm.name.trim())return toast.error('Enter customer name.');const normalizedGstin=customerForm.gstin.replace(/\s+/g,'').toUpperCase();if(normalizedGstin && !/^\d{15}$/.test(normalizedGstin) && !/^[A-Z0-9]{15}$/.test(normalizedGstin))return toast.error('GSTIN must be exactly 15 letters/numbers.');setCustomerSaving(true);try{const payload={customer_type:'business',name:customerForm.name.trim(),gstin:normalizedGstin||null,pan:customerForm.pan.trim()||null,billing_address_line1:customerForm.billing_address_line1.trim()||null,billing_city:customerForm.billing_city.trim()||null,billing_state:customerForm.billing_state.trim()||null,billing_pincode:customerForm.billing_pincode.trim()||null,place_of_supply:customerForm.place_of_supply.trim()||customerForm.billing_state.trim()||null,customer_state_code:customerForm.customer_state_code.trim()||gstState(customerForm.gstin),active:true};const query=editingCustomer?supabase.from('billing_customers').update(payload).eq('id',editingCustomer.id):supabase.from('billing_customers').insert(payload);const {data,error}=await query.select().single();if(error)throw error;setCustomers(x=>{const next=editingCustomer?x.map(r=>r.id===data.id?data:r):[...x,data];return next.sort((a,b)=>a.name.localeCompare(b.name))});setCustomer(data.id);setCustomerModal(false);setCustomerForm(emptyCustomerForm);setEditingCustomer(null);toast.success(editingCustomer?'Customer updated':'Customer added')}catch(e){toast.error(e.message||'Customer creation failed')}finally{setCustomerSaving(false)}};
 const addInventory=async e=>{e.preventDefault();if(!inventoryForm.product_name.trim())return toast.error('Enter item name.');if(!inventoryForm.selling_price || +inventoryForm.selling_price<0)return toast.error('Enter a valid rate.');if(inventoryForm.gst_rate==='' || +inventoryForm.gst_rate<0)return toast.error('Enter a valid GST rate.');setInventorySaving(true);try{const payload={product_name:inventoryForm.product_name.trim(),hsn:'996749',unit:'KWH',purchase_price:inventoryForm.purchase_price===''?null:+inventoryForm.purchase_price,selling_price:+inventoryForm.selling_price,gst_rate:+inventoryForm.gst_rate,stock_tracked:false,stock_qty:0,min_stock_qty:0,batch_no:null,expiry_date:null,supplier_name:null,notes:inventoryForm.notes.trim()||null,inventory_type:'electricity',active:true};const query=editingInventory?supabase.from('inventory').update(payload).eq('id',editingInventory.id):supabase.from('inventory').insert(payload);const {data,error}=await query.select().single();if(error)throw error;setInventory(x=>{const next=editingInventory?x.map(r=>r.id===data.id?data:r):[...x,data];return next.sort((a,b)=>a.product_name.localeCompare(b.product_name))});setInventoryModal(false);setInventoryForm(emptyInventoryForm);setEditingInventory(null);toast.success(editingInventory?'Billing item updated':'Billing item added');if(!items.length)setItems([{inventory_id:data.id,description:data.product_name,hsn:data.hsn||'',unit:data.unit||'KWH',quantity:1,unit_price:+data.selling_price||0,gst_rate:+data.gst_rate||0,discount_percent:0}]);}catch(e){toast.error(e.message||'Billing item creation failed')}finally{setInventorySaving(false)}};
 const save=async()=>{if(!c)return toast.error('Select a customer.');if(!from||!to||new Date(from)>new Date(to))return toast.error('Enter a valid billing period.');if(!station.trim())return toast.error('Enter the charging station.');if(!items.length)return toast.error('Add at least one item.');setSaving(true);try{const {data:num,error:ne}=await supabase.rpc('next_billing_invoice_number',{p_series:series.trim()});if(ne)throw ne;const {data:u}=await supabase.auth.getUser();const p={invoice_number:num,invoice_series:series.trim(),invoice_date:new Date().toISOString().slice(0,10),customer_id:c.id,billing_name:c.name,billing_gstin:c.gstin||null,billing_pan:c.pan||null,billing_address_line1:c.billing_address_line1,billing_address_line2:c.billing_address_line2,billing_city:c.billing_city,billing_state:c.billing_state,billing_state_code:c.billing_state_code,billing_pincode:c.billing_pincode,billing_country:c.billing_country||'India',place_of_supply:c.place_of_supply||c.billing_state||'',place_of_supply_state_code:c.customer_state_code||gstState(c.gstin),station:station.trim(),billing_period_from:from,billing_period_to:to,subtotal:total.taxable,discount_total:0,taxable_amount:total.taxable,cgst_amount:total.cgst,sgst_amount:total.sgst,igst_amount:total.igst,cess_amount:0,total_tax:total.tax,round_off:total.round,grand_total:total.total,invoice_status:'issued',created_by:u.user?.id||null};const {data:inv,error:ie}=await supabase.from('billing_invoices').insert(p).select().single();if(ie)throw ie;const rows=total.rows.map(x=>({invoice_id:inv.id,inventory_id:x.inventory_id,description:x.description,hsn:x.hsn||null,unit:x.unit,quantity:+x.quantity,unit_price:+x.unit_price,discount_percent:+x.discount_percent||0,discount_amount:x.discount_amount,taxable_amount:x.taxable_amount,gst_rate:+x.gst_rate,cgst_rate:taxType==='CGST_SGST'?+x.gst_rate/2:0,cgst_amount:taxType==='CGST_SGST'?x.taxable_amount*+x.gst_rate/200:0,sgst_rate:taxType==='CGST_SGST'?+x.gst_rate/2:0,sgst_amount:taxType==='CGST_SGST'?x.taxable_amount*+x.gst_rate/200:0,igst_rate:taxType==='IGST'?+x.gst_rate:0,igst_amount:taxType==='IGST'?x.taxable_amount*+x.gst_rate/100:0,cess_rate:0,cess_amount:0,line_total:x.line_total,tax_type:taxType}));const {data:saved,error:se}=await supabase.from('billing_invoice_items').insert(rows).select();if(se)throw se;setInvoices(x=>[inv,...x]);setItems([]);setCustomer('');setStation('');setFrom('');setTo('');setTab('invoices');toast.success('EV Billing invoice created');pdf(inv,saved,settings).save(inv.invoice_number+'.pdf');}catch(e){toast.error(e.message||'Invoice creation failed')}finally{setSaving(false)}};
 const download=async inv=>{const [{data:i,error:ie}]=await Promise.all([supabase.from('billing_invoice_items').select('*').eq('invoice_id',inv.id).order('created_at')]);if(ie)return toast.error(ie.message);pdf(inv,i,settings).save(inv.invoice_number+'.pdf')};
 const deleteInvoice=async inv=>{if(!window.confirm('Delete invoice '+inv.invoice_number+'? Its invoice items will also be deleted.'))return;const {error}=await supabase.from('billing_invoices').delete().eq('id',inv.id);if(error)return toast.error(error.message);setInvoices(x=>x.filter(r=>r.id!==inv.id));toast.success('Invoice deleted')};
 const deleteCustomer=async row=>{if(!window.confirm('Delete customer '+row.name+'?'))return;const {count,error:ce}=await supabase.from('billing_invoices').select('id',{count:'exact',head:true}).eq('customer_id',row.id);if(ce)return toast.error(ce.message);if(count)return toast.error('Customer cannot be deleted because invoices exist for this customer.');const {error}=await supabase.from('billing_customers').delete().eq('id',row.id);if(error)return toast.error(error.message);setCustomers(x=>x.filter(r=>r.id!==row.id));toast.success('Customer deleted')};
 const deleteInventory=async row=>{if(!window.confirm('Delete billing item '+row.product_name+'?'))return;const {count,error:ce}=await supabase.from('billing_invoice_items').select('id',{count:'exact',head:true}).eq('inventory_id',row.id);if(ce)return toast.error(ce.message);if(count)return toast.error('Billing item cannot be deleted because it is used on invoices. Deactivate it instead.');const {error}=await supabase.from('inventory').delete().eq('id',row.id);if(error)return toast.error(error.message);setInventory(x=>x.filter(r=>r.id!==row.id));toast.success('Charging item deleted')};

 return <div className="page-container">
  <div className="page-header"><div><h1>EV Billing</h1><p>Triarc EV charging tax invoices</p></div><div><button className="btn btn-secondary" onClick={()=>load()}><RefreshCw size={14}/> Refresh</button> <button className="btn btn-primary" onClick={()=>setTab('new')}><Plus size={14}/> New EV Billing</button></div></div>
  <div className="tabs"><button className={tab==='invoices'?'tab active':'tab'} onClick={()=>setTab('invoices')}>Invoices</button><button className={tab==='new'?'tab active':'tab'} onClick={()=>setTab('new')}>New Invoice</button><button className={tab==='customers'?'tab active':'tab'} onClick={()=>setTab('customers')}>Customers</button><button className={tab==='billing-items'?'tab active':'tab'} onClick={()=>setTab('billing-items')}>Billing Items</button><button className={tab==='assets'?'tab active':'tab'} onClick={()=>setTab('assets')}>Asset Register</button></div>
  {tab==='invoices'&&<div className="card"><div className="table-container"><table><thead><tr><th>Invoice No.</th><th>Date</th><th>Customer</th><th>Place of Supply</th><th>Station</th><th>Total</th><th></th></tr></thead><tbody>{invoices.map(i=><tr key={i.id}><td>{i.invoice_number}</td><td>{fmtDate(i.invoice_date)}</td><td>{i.billing_name}</td><td>{i.place_of_supply||'-'}</td><td>{i.station||'-'}</td><td>₹{money(i.grand_total)}</td><td><div style={{display:'flex',gap:6}}><button className="btn btn-secondary" onClick={()=>download(i)}><Download size={14}/> PDF</button><button className="btn btn-secondary" onClick={()=>deleteInvoice(i)}><Trash2 size={14}/> Delete</button></div></td></tr>)}{!invoices.length&&<tr><td colSpan="7">No EV invoices yet.</td></tr>}</tbody></table></div></div>}
  {tab==='customers'&&<div className="card"><div className="page-header"><div><h2>Customer Management</h2><p>Manage customers used for GST invoices.</p></div><button className="btn btn-primary" onClick={()=>openCustomer()}><Plus size={14}/> Add Customer</button></div><div className="table-container"><table><thead><tr><th>Customer</th><th>GSTIN</th><th>PAN</th><th>Place of Supply</th><th>State Code</th><th>Status</th><th></th></tr></thead><tbody>{customers.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.gstin||'-'}</td><td>{r.pan||'-'}</td><td>{r.place_of_supply||r.billing_state||'-'}</td><td>{r.customer_state_code||'-'}</td><td>{r.active?'Active':'Inactive'}</td><td><div style={{display:'flex',gap:6}}><button className="btn btn-secondary" onClick={()=>openCustomer(r)}>Edit</button><button className="btn btn-secondary" onClick={()=>deleteCustomer(r)}><Trash2 size={14}/> Delete</button></div></td></tr>)}{!customers.length&&<tr><td colSpan="7">No customers yet.</td></tr>}</tbody></table></div></div>}
  {tab==='assets'&&<div className="card"><div className="page-header"><div><h2>Asset Register</h2><p>Track chargers, cameras, NVRs and other physical EV station equipment.</p></div><button className="btn btn-primary" onClick={()=>openAsset()}><Plus size={14}/> Add Asset</button></div><div className="table-container"><table><thead><tr><th>Type</th><th>Name</th><th>Company</th><th>Model</th><th>Serial Number</th><th>IP</th><th>MAC</th><th>Site</th><th>Status</th><th></th></tr></thead><tbody>{assets.map(r=><tr key={r.id}><td>{r.asset_type.toUpperCase()}</td><td>{r.name}</td><td>{r.manufacturer||'-'}</td><td>{r.model||'-'}</td><td>{r.serial_number||'-'}</td><td>{r.ip_address||'-'}</td><td>{r.mac_address||'-'}</td><td>{r.site||'-'}</td><td>{r.status}</td><td><div style={{display:'flex',gap:6}}><button className="btn btn-secondary" onClick={()=>openAsset(r)}>Edit</button><button className="btn btn-secondary" onClick={()=>deleteAsset(r)}><Trash2 size={14}/></button></div></td></tr>)}{!assets.length&&<tr><td colSpan="10">No assets yet.</td></tr>}</tbody></table></div></div>}
  {tab==='billing-items'&&<div className="card"><div className="page-header"><div><h2>Billing Items</h2><p>Billable EV charging services. Item names are entered manually.</p></div><button className="btn btn-primary" onClick={()=>openInventory()}><Plus size={14}/> Add Billing Item</button></div><div className="table-container"><table><thead><tr><th>Item Name</th><th>HSN/SAC</th><th>Unit</th><th>Rate / KWH</th><th>GST</th><th></th></tr></thead><tbody>{inventory.map(r=><tr key={r.id}><td>{r.product_name}</td><td>{r.hsn||'996749'}</td><td>{r.unit||'KWH'}</td><td>₹{money(r.selling_price)}</td><td>{r.gst_rate}%</td><td><div style={{display:'flex',gap:6}}><button className="btn btn-secondary" onClick={()=>openInventory(r)}>Edit</button><button className="btn btn-secondary" onClick={()=>deleteInventory(r)}><Trash2 size={14}/></button></div></td></tr>)}{!inventory.length&&<tr><td colSpan="6">No billing items yet.</td></tr>}</tbody></table></div></div>}
  {tab==='new'&&<div className="card"><h2>New EV Billing Invoice</h2><div className="form-grid">
    <label>Customer<div className="field-with-action"><select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">Select customer</option>{customers.map(x=><option value={x.id} key={x.id}>{x.name}{x.gstin?' — '+x.gstin:''}</option>)}</select><button type="button" className="btn btn-secondary" title="Add customer" onClick={()=>openCustomer()}><Plus size={14}/></button></div></label>
    <label>Invoice Series<input value={series} onChange={e=>setSeries(e.target.value)}/></label>
    <label>Station<input value={station} onChange={e=>setStation(e.target.value)} placeholder="Triarc EV Hub | Bhadrachalam"/></label>
    <label>Place of Supply<input value={c?.place_of_supply||c?.billing_state||''} readOnly/></label>
    <label>Billing Period From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label>
    <label>Billing Period To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label>
    <label>GST Type{auto?<input value={auto===TRIARC_STATE?'CGST + SGST':'IGST'} readOnly/>:<select value={manualTax} onChange={e=>setManualTax(e.target.value)}><option value="CGST_SGST">CGST + SGST</option><option value="IGST">IGST</option></select>}</label>
   </div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:20}}><h3>Charging Items</h3><div style={{display:'flex',gap:8}}><button className="btn btn-secondary" onClick={()=>inventory.length?add():setInventoryModal(true)}><Plus size={14}/> Add Item</button><button className="btn btn-secondary" onClick={()=>openInventory()}><Plus size={14}/> New Item</button></div></div>
   <div className="table-container"><table><thead><tr><th>Item</th><th>HSN/SAC</th><th>Qty</th><th>Unit</th><th>Rate</th><th>GST%</th><th></th></tr></thead><tbody>{items.map((x,i)=><tr key={i}><td><select value={x.inventory_id} onChange={e=>pick(i,e.target.value)}>{inventory.map(p=><option key={p.id} value={p.id}>{p.product_name}</option>)}</select></td><td>{x.hsn||'-'}</td><td><input type="number" min="0" step="0.001" value={x.quantity} onChange={e=>setItems(r=>r.map((z,n)=>n===i?{...z,quantity:e.target.value}:z))}/></td><td>{x.unit}</td><td><input type="number" min="0" step="0.01" value={x.unit_price} onChange={e=>setItems(r=>r.map((z,n)=>n===i?{...z,unit_price:e.target.value}:z))}/></td><td>{x.gst_rate}%</td><td><button className="btn btn-secondary" onClick={()=>setItems(r=>r.filter((_,n)=>n!==i))}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>
   <div style={{maxWidth:320,marginLeft:'auto',marginTop:16}}><div className="summary-row"><span>Taxable Amount</span><b>₹{money(total.taxable)}</b></div>{taxType==='IGST'?<div className="summary-row"><span>IGST</span><b>₹{money(total.igst)}</b></div>:<><div className="summary-row"><span>CGST</span><b>₹{money(total.cgst)}</b></div><div className="summary-row"><span>SGST</span><b>₹{money(total.sgst)}</b></div></>}<div className="summary-row"><span>Round Off</span><b>₹{money(total.round)}</b></div><div className="summary-row total"><span>Total</span><b>₹{money(total.total)}</b></div></div>
   <div style={{textAlign:'right',marginTop:16}}><button className="btn btn-primary" disabled={saving} onClick={save}>{saving?'Creating…':'Create EV Billing Invoice'}</button></div>
  </div>}
  {customerModal&&<Modal title={editingCustomer?"Edit Customer":"Add Customer"} onClose={()=>setCustomerModal(false)}><form onSubmit={addCustomer}><div className="customer-master-note">EV Billing Customer Master · Business customer</div><div className="form-grid modal-grid">
    <label>Customer Name *<input autoFocus value={customerForm.name} onChange={e=>setCustomerForm({...customerForm,name:e.target.value})} placeholder="Customer / Company Name"/></label><label>GSTIN<input maxLength="15" value={customerForm.gstin} onChange={e=>setCustomerForm({...customerForm,gstin:e.target.value.toUpperCase()})}/></label><label>PAN<input maxLength="10" value={customerForm.pan} onChange={e=>setCustomerForm({...customerForm,pan:e.target.value.toUpperCase()})}/></label><label>Billing Address<input value={customerForm.billing_address_line1} onChange={e=>setCustomerForm({...customerForm,billing_address_line1:e.target.value})}/></label><label>City<input value={customerForm.billing_city} onChange={e=>setCustomerForm({...customerForm,billing_city:e.target.value})}/></label><label>State<input value={customerForm.billing_state} onChange={e=>setCustomerForm({...customerForm,billing_state:e.target.value})}/></label><label>Pincode<input value={customerForm.billing_pincode} onChange={e=>setCustomerForm({...customerForm,billing_pincode:e.target.value})}/></label><label>Place of Supply<input value={customerForm.place_of_supply} onChange={e=>setCustomerForm({...customerForm,place_of_supply:e.target.value})} placeholder="Kerala"/></label><label>State Code<input maxLength="2" value={customerForm.customer_state_code || gstState(customerForm.gstin) || ''} onChange={e=>setCustomerForm({...customerForm,customer_state_code:e.target.value.replace(/\D/g,'').slice(0,2)})} placeholder="Auto from GSTIN"/></label>
   </div><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setCustomerModal(false)}>Cancel</button><button className="btn btn-primary" disabled={customerSaving}>{customerSaving?'Saving…':editingCustomer?'Save Changes':'Add Customer'}</button></div></form></Modal>}
  {assetModal&&<Modal title={editingAsset?"Edit Asset":"Add Asset"} onClose={()=>setAssetModal(false)}><form onSubmit={saveAsset}><div className="form-grid modal-grid">
<label>Asset Type *<select value={assetForm.asset_type} onChange={e=>setAssetForm({...assetForm,asset_type:e.target.value})}><option value="charger">EV Charger</option><option value="camera">Camera</option><option value="nvr">NVR</option></select></label><label>Name *<input autoFocus value={assetForm.name} onChange={e=>setAssetForm({...assetForm,name:e.target.value})} placeholder={assetForm.asset_type==='charger'?'60kW DC Charger':assetForm.asset_type==='camera'?'PoE Camera':'8 Channel NVR'}/></label><label>Company / Manufacturer<input value={assetForm.manufacturer} onChange={e=>setAssetForm({...assetForm,manufacturer:e.target.value})}/></label><label>Model<input value={assetForm.model} onChange={e=>setAssetForm({...assetForm,model:e.target.value})}/></label><label>Serial Number<input value={assetForm.serial_number} onChange={e=>setAssetForm({...assetForm,serial_number:e.target.value})}/></label><label>Asset Tag<input value={assetForm.asset_tag} onChange={e=>setAssetForm({...assetForm,asset_tag:e.target.value})}/></label><label>Site<input value={assetForm.site} onChange={e=>setAssetForm({...assetForm,site:e.target.value})}/></label><label>Location<input value={assetForm.location} onChange={e=>setAssetForm({...assetForm,location:e.target.value})}/></label><label>Status<select value={assetForm.status} onChange={e=>setAssetForm({...assetForm,status:e.target.value})}><option value="active">Active</option><option value="inactive">Inactive</option><option value="maintenance">Maintenance</option><option value="retired">Retired</option></select></label><label>IP Address<input value={assetForm.ip_address} onChange={e=>setAssetForm({...assetForm,ip_address:e.target.value})}/></label><label>MAC Address<input value={assetForm.mac_address} onChange={e=>setAssetForm({...assetForm,mac_address:e.target.value})}/></label><label>Firmware Version<input value={assetForm.firmware_version} onChange={e=>setAssetForm({...assetForm,firmware_version:e.target.value})}/></label><label>Purchase Date<input type="date" value={assetForm.purchase_date} onChange={e=>setAssetForm({...assetForm,purchase_date:e.target.value})}/></label><label>Installation Date<input type="date" value={assetForm.installation_date} onChange={e=>setAssetForm({...assetForm,installation_date:e.target.value})}/></label><label>Warranty Start<input type="date" value={assetForm.warranty_start} onChange={e=>setAssetForm({...assetForm,warranty_start:e.target.value})}/></label><label>Warranty End<input type="date" value={assetForm.warranty_end} onChange={e=>setAssetForm({...assetForm,warranty_end:e.target.value})}/></label>
{assetForm.asset_type==='charger'&&<><label>Rated Power (kW)<input value={assetForm.details.rated_power_kw} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,rated_power_kw:e.target.value}})} placeholder="60"/></label><label>Connector Type<input value={assetForm.details.connector_type} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,connector_type:e.target.value}})} placeholder="CCS2"/></label><label>Connector Count<input value={assetForm.details.connector_count} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,connector_count:e.target.value}})}/></label><label>Input Voltage<input value={assetForm.details.input_voltage} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,input_voltage:e.target.value}})}/></label><label>Output Voltage<input value={assetForm.details.output_voltage} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,output_voltage:e.target.value}})}/></label><label>Max Current<input value={assetForm.details.max_current} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,max_current:e.target.value}})}/></label><label>Meter Serial Number<input value={assetForm.details.meter_serial} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,meter_serial:e.target.value}})}/></label><label>OCPP Version<input value={assetForm.details.ocpp_version} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,ocpp_version:e.target.value}})}/></label><label>Network Type<input value={assetForm.details.network_type} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,network_type:e.target.value}})}/></label>}
{assetForm.asset_type==='camera'&&<><label>Resolution<input value={assetForm.details.camera_resolution} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,camera_resolution:e.target.value}})} placeholder="4MP"/></label><label>Lens<input value={assetForm.details.lens} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,lens:e.target.value}})}/></label><label>PoE<input value={assetForm.details.poe} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,poe:e.target.value}})}/></label></>}
{assetForm.asset_type==='nvr'&&<><label>Channels<input value={assetForm.details.nvr_channels} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,nvr_channels:e.target.value}})} placeholder="8"/></label><label>Storage Capacity<input value={assetForm.details.storage_capacity} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,storage_capacity:e.target.value}})}/></label><label>HDD Serial Number<input value={assetForm.details.hdd_serial} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,hdd_serial:e.target.value}})}/></label><label>HDD Count<input value={assetForm.details.hdd_count} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,hdd_count:e.target.value}})}/></label><label>PoE Ports<input value={assetForm.details.poe_ports} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,poe_ports:e.target.value}})}/></label><label>Connected Cameras<input value={assetForm.details.connected_cameras} onChange={e=>setAssetForm({...assetForm,details:{...assetForm.details,connected_cameras:e.target.value}})}/></label></>}
<label style={{gridColumn:'1/-1'}}>Notes<textarea value={assetForm.notes} onChange={e=>setAssetForm({...assetForm,notes:e.target.value})} rows="3"/></label>
</div><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setAssetModal(false)}>Cancel</button><button className="btn btn-primary" disabled={assetSaving}>{assetSaving?'Saving…':editingAsset?'Save Changes':'Add Asset'}</button></div></form></Modal>}
  {inventoryModal&&<Modal title={editingInventory?"Edit Billing Item":"Add Billing Item"} onClose={()=>setInventoryModal(false)}><form onSubmit={addInventory}><div className="form-grid modal-grid">
    <label>Item Name *<input autoFocus value={inventoryForm.product_name} onChange={e=>setInventoryForm({...inventoryForm,product_name:e.target.value})} placeholder="e.g. DC EV Charging"/></label>
    <label>HSN/SAC<input value="996749" readOnly/></label>
    <label>Unit<input value="KWH" readOnly/></label>
    <label>Purchase Price<input type="number" min="0" step="0.01" value={inventoryForm.purchase_price} onChange={e=>setInventoryForm({...inventoryForm,purchase_price:e.target.value})}/></label>
    <label>Selling Price / KWH *<input type="number" min="0" step="0.01" value={inventoryForm.selling_price} onChange={e=>setInventoryForm({...inventoryForm,selling_price:e.target.value})}/></label>
    <label>GST % *<input type="number" min="0" step="0.01" value={inventoryForm.gst_rate} onChange={e=>setInventoryForm({...inventoryForm,gst_rate:e.target.value})}/></label>
    <label>Notes<input value={inventoryForm.notes} onChange={e=>setInventoryForm({...inventoryForm,notes:e.target.value})}/></label>
   </div><p className="muted modal-note">EV charging is billed in kWh. HSN/SAC 996749 and unit KWH are fixed. Billing Items contain only billable charging-service information.</p><div className="modal-actions"><button type="button" className="btn btn-secondary" onClick={()=>setInventoryModal(false)}>Cancel</button><button className="btn btn-primary" disabled={inventorySaving}>{inventorySaving?'Saving…':editingInventory?'Save Changes':'Add Item'}</button></div></form></Modal>}
 </div>;
}
